### ISSUE TITLE
代码是否还没完全开源？

### ISSUE THREAD

**Issue by numb0824** [SunZezhou/Active-SLAM-with-Cartographer#1]
大佬您好，我看了一下仓库里面的内容，是否这部分的代码还没开源？

**Comment by SunZZ528** [comment]
你好，我们代码是全部开源的，但由于我们实物测试的机器人驱动大概率与其他使用者不同，因此我们修改了部分代码使其能在仿真环境中复现，所以代码中可能存在没有删除干净的配置文件。谢谢你的关注～

**Comment by SunZezhou** [comment]
你好，我们代码是全部开源的，但由于我们实物测试的机器人驱动大概率与其他使用者不同，因此我们修改了部分代码使其能在仿真环境中复现，代码中可能会存在没有删除干净的配置文件。谢谢你的关注～
